# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: venue_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "VenueMessage" do
    optional :id, :int32, 1
    optional :artist, :message, 2, "ArtistMessage"
    optional :location, :message, 3, "VenueMessage.LocationMessage"
    optional :venue_date, :string, 4
  end
  add_message "VenueMessage.LocationMessage" do
    optional :country, :string, 1
    optional :city, :string, 2
    optional :place, :string, 3
  end
end

VenueMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("VenueMessage").msgclass
VenueMessage::LocationMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("VenueMessage.LocationMessage").msgclass
